/**
 * useContract Hook
 * Central hook for all smart contract interactions via ethers.js + MetaMask
 * Vite/ESM version — uses import.meta.env instead of process.env
 */

import { useState, useEffect, useCallback } from 'react'
import { ethers } from 'ethers'

// contractConfig.json is auto-generated by scripts/deploy.js after deployment.
// We use a dynamic import with a fallback so the app still loads pre-deployment.
let _config = null
try {
  // Vite supports JSON imports natively (static import works at module load)
  // We use a try/catch so the app doesn't crash before deployment.
  const raw = await import('../contractConfig.json')
  _config = raw.default
} catch {
  _config = null
}

const contractConfig = _config ?? {
  contractAddress: import.meta.env.VITE_CONTRACT_ADDRESS ?? '',
  abi: [],
  chainId: 11155111,
}

export const CONTRACT_ADDRESS = contractConfig.contractAddress
export const CONTRACT_ABI = contractConfig.abi

// ─────────────────────────────────────────────────────────────
//  WALLET CONNECTION
// ─────────────────────────────────────────────────────────────

export function useWallet() {
  const [account, setAccount] = useState(null)
  const [provider, setProvider] = useState(null)
  const [signer, setSigner] = useState(null)
  const [chainId, setChainId] = useState(null)
  const [isConnecting, setIsConnecting] = useState(false)
  const [error, setError] = useState(null)

  const isMetaMaskInstalled = () =>
    typeof window !== 'undefined' && Boolean(window.ethereum)

  const connectWallet = useCallback(async () => {
    if (!isMetaMaskInstalled()) {
      setError('MetaMask not installed. Please install MetaMask to continue.')
      return null
    }
    try {
      setIsConnecting(true)
      setError(null)

      const _provider = new ethers.BrowserProvider(window.ethereum)
      await _provider.send('eth_requestAccounts', [])

      const _signer = await _provider.getSigner()
      const _account = await _signer.getAddress()
      const network = await _provider.getNetwork()

      setProvider(_provider)
      setSigner(_signer)
      setAccount(_account)
      setChainId(Number(network.chainId))

      return { provider: _provider, signer: _signer, account: _account }
    } catch (err) {
      setError(err.message || 'Failed to connect wallet')
      return null
    } finally {
      setIsConnecting(false)
    }
  }, [])

  const disconnectWallet = useCallback(() => {
    setAccount(null)
    setProvider(null)
    setSigner(null)
    setChainId(null)
  }, [])

  useEffect(() => {
  if (!isMetaMaskInstalled()) return

  // ✅ Only restore session if user already explicitly connected before
  // eth_accounts returns connected accounts WITHOUT triggering a popup
  // We only restore — never auto-prompt
  window.ethereum.request({ method: 'eth_accounts' }).then((accounts) => {
    if (accounts.length > 0) {
      // Silently restore existing session — no popup
      const _provider = new ethers.BrowserProvider(window.ethereum)
      _provider.getSigner().then(async (_signer) => {
        const _account = await _signer.getAddress()
        const network  = await _provider.getNetwork()
        setProvider(_provider)
        setSigner(_signer)
        setAccount(_account)
        setChainId(Number(network.chainId))
      }).catch(() => {
        // Session expired — don't auto-prompt, just stay disconnected
      })
    }
    // If no accounts → stay disconnected, wait for user to click Connect
  })

  const handleAccountsChanged = (accounts) => {
    if (accounts.length === 0) disconnectWallet()
    else {
      // Account switched — silently update, no popup
      const _provider = new ethers.BrowserProvider(window.ethereum)
      _provider.getSigner().then(async (_signer) => {
        const _account = await _signer.getAddress()
        const network  = await _provider.getNetwork()
        setProvider(_provider)
        setSigner(_signer)
        setAccount(_account)
        setChainId(Number(network.chainId))
      }).catch(() => disconnectWallet())
    }
  }

  const handleChainChanged = () => window.location.reload()

  window.ethereum.on('accountsChanged', handleAccountsChanged)
  window.ethereum.on('chainChanged', handleChainChanged)

  return () => {
    window.ethereum.removeListener('accountsChanged', handleAccountsChanged)
    window.ethereum.removeListener('chainChanged', handleChainChanged)
  }
}, [disconnectWallet])

  return {
    account,
    provider,
    signer,
    chainId,
    isConnecting,
    error,
    connectWallet,
    disconnectWallet,
    isConnected: Boolean(account),
    isMetaMaskInstalled: isMetaMaskInstalled(),
  }
}

// ─────────────────────────────────────────────────────────────
//  CONTRACT INTERACTION HOOK
// ─────────────────────────────────────────────────────────────

export function useContract(signer) {
  const getContract = useCallback(
    (readOnly = false) => {
      if (!CONTRACT_ADDRESS || !CONTRACT_ABI.length) {
        throw new Error(
          'Contract not configured. Deploy first: npm run deploy:local'
        )
      }
      if (readOnly) {
        const provider = new ethers.JsonRpcProvider(
          import.meta.env.VITE_RPC_URL ?? 'http://127.0.0.1:8545'
        )
        return new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, provider)
      }
      if (!signer) throw new Error('Wallet not connected')
      return new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, signer)
    },
    [signer]
  )

  const registerPatient = useCallback(
    async (name, age) => {
      const tx = await getContract().registerPatient(name, age)
      return tx.wait()
    },
    [getContract]
  )

  const getPatient = useCallback(
    async (address) => {
      const p = await getContract(true).getPatient(address)
      return {
        wallet: p.wallet,
        name: p.name,
        age: Number(p.age),
        registered: p.registered,
        registeredAt: Number(p.registeredAt),
      }
    },
    [getContract]
  )

  const registerDoctorSelf = useCallback(
    async (name, specialization) => {
      const tx = await getContract().registerDoctorSelf(name, specialization)
      return tx.wait()
    },
    [getContract]
  )

  const getDoctor = useCallback(
    async (address) => {
      const d = await getContract(true).getDoctor(address)
      return {
        wallet: d.wallet,
        name: d.name,
        specialization: d.specialization,
        registered: d.registered,
        registeredAt: Number(d.registeredAt),
      }
    },
    [getContract]
  )

  const grantAccess = useCallback(
    async (doctorAddress) => {
      const tx = await getContract().grantAccess(doctorAddress)
      return tx.wait()
    },
    [getContract]
  )

  const revokeAccess = useCallback(
    async (doctorAddress) => {
      const tx = await getContract().revokeAccess(doctorAddress)
      return tx.wait()
    },
    [getContract]
  )

  const checkAccess = useCallback(
    async (patientAddress, doctorAddress) => {
      return getContract(true).checkAccess(patientAddress, doctorAddress)
    },
    [getContract]
  )

  const addMedicalRecord = useCallback(
    async (patientAddress, ipfsHash, description, recordType) => {
      const tx = await getContract().addMedicalRecord(
        patientAddress,
        ipfsHash,
        description,
        recordType
      )
      return tx.wait()
    },
    [getContract]
  )

  const getRecords = useCallback(
    async (patientAddress) => {
      const records = await getContract(true).getRecords(patientAddress)
      return records.map((r) => ({
        ipfsHash: r.ipfsHash,
        description: r.description,
        doctorAddress: r.doctorAddress,
        timestamp: Number(r.timestamp),
        recordType: r.recordType,
      }))
    },
    [getContract]
  )

  const getAccessLogs = useCallback(
    async (patientAddress) => {
      const logs = await getContract().getAccessLogs(patientAddress)
      return logs.map((l) => ({
        viewer: l.viewer,
        timestamp: Number(l.timestamp),
        action: l.action,
      }))
    },
    [getContract]
  )

  const isPatientRegistered = useCallback(
    async (address) => {
      try {
        const p = await getContract(true).patients(address)
        return p.registered
      } catch {
        return false
      }
    },
    [getContract]
  )

  const isDoctorRegistered = useCallback(
    async (address) => {
      try {
        const d = await getContract(true).doctors(address)
        return d.registered
      } catch {
        return false
      }
    },
    [getContract]
  )

  return {
    registerPatient,
    getPatient,
    registerDoctorSelf,
    getDoctor,
    grantAccess,
    revokeAccess,
    checkAccess,
    addMedicalRecord,
    getRecords,
    getAccessLogs,
    isPatientRegistered,
    isDoctorRegistered,
  }
}
